-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.4d)
-- from file main.cph, on 2018-05-11 at 12:39:30, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package edgeDetectionOk_globals is
  type array64_u8 is array (0 to 63) of unsigned(7 downto 0);
  type array64_b is array (0 to 63) of boolean;
function fabs(x:signed(13 downto 0)) return signed;
end edgeDetectionOk_globals;

package body edgeDetectionOk_globals is
function fabs(x:signed(13 downto 0)) return signed is
  begin
    return cond((x) < (0),-(x),x);
  end fabs;
end edgeDetectionOk_globals;
